//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Prefabs/InputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace Input
{
    public partial class @InputActions : IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @InputActions()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActions"",
    ""maps"": [
        {
            ""name"": ""General Controls"",
            ""id"": ""775ec2b0-db0d-4234-a6cd-4343c9be6f27"",
            ""actions"": [
                {
                    ""name"": ""Open Settings"",
                    ""type"": ""Button"",
                    ""id"": ""0f7bb646-95bd-493b-ad3e-9907993e519f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""4e321777-61fc-4458-a6db-1bf6cb0b93d1"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Mouse and Keyboard"",
                    ""action"": ""Open Settings"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Mouse and Keyboard"",
            ""bindingGroup"": ""Mouse and Keyboard"",
            ""devices"": [
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
            // General Controls
            m_GeneralControls = asset.FindActionMap("General Controls", throwIfNotFound: true);
            m_GeneralControls_OpenSettings = m_GeneralControls.FindAction("Open Settings", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }
        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }
        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // General Controls
        private readonly InputActionMap m_GeneralControls;
        private IGeneralControlsActions m_GeneralControlsActionsCallbackInterface;
        private readonly InputAction m_GeneralControls_OpenSettings;
        public struct GeneralControlsActions
        {
            private @InputActions m_Wrapper;
            public GeneralControlsActions(@InputActions wrapper) { m_Wrapper = wrapper; }
            public InputAction @OpenSettings => m_Wrapper.m_GeneralControls_OpenSettings;
            public InputActionMap Get() { return m_Wrapper.m_GeneralControls; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(GeneralControlsActions set) { return set.Get(); }
            public void SetCallbacks(IGeneralControlsActions instance)
            {
                if (m_Wrapper.m_GeneralControlsActionsCallbackInterface != null)
                {
                    @OpenSettings.started -= m_Wrapper.m_GeneralControlsActionsCallbackInterface.OnOpenSettings;
                    @OpenSettings.performed -= m_Wrapper.m_GeneralControlsActionsCallbackInterface.OnOpenSettings;
                    @OpenSettings.canceled -= m_Wrapper.m_GeneralControlsActionsCallbackInterface.OnOpenSettings;
                }
                m_Wrapper.m_GeneralControlsActionsCallbackInterface = instance;
                if (instance != null)
                {
                    @OpenSettings.started += instance.OnOpenSettings;
                    @OpenSettings.performed += instance.OnOpenSettings;
                    @OpenSettings.canceled += instance.OnOpenSettings;
                }
            }
        }
        public GeneralControlsActions @GeneralControls => new GeneralControlsActions(this);
        private int m_MouseandKeyboardSchemeIndex = -1;
        public InputControlScheme MouseandKeyboardScheme
        {
            get
            {
                if (m_MouseandKeyboardSchemeIndex == -1) m_MouseandKeyboardSchemeIndex = asset.FindControlSchemeIndex("Mouse and Keyboard");
                return asset.controlSchemes[m_MouseandKeyboardSchemeIndex];
            }
        }
        public interface IGeneralControlsActions
        {
            void OnOpenSettings(InputAction.CallbackContext context);
        }
    }
}
